TOKEN(None), 
TOKEN(Comma),
TOKEN(Assign),
TOKEN(AddAssign),
TOKEN(SubtractAssign),
TOKEN(MultiplyAssign),
TOKEN(DivideAssign),
TOKEN(ModulusAssign),
TOKEN(ShiftLeftAssign), TOKEN(ShiftRightAssign), TOKEN(ArithmeticAndAssign), TOKEN(ArithmeticOrAssign), TOKEN(ArithmeticExorAssign),
TOKEN(QuestionMark), TOKEN(Colon), 
TOKEN(LogicalOr), 
TOKEN(LogicalAnd), 
TOKEN(ArithmeticOr), 
TOKEN(ArithmeticExor), 
TOKEN(Ampersand), 
TOKEN(Equal), TOKEN(NotEqual), 
TOKEN(LessThan), TOKEN(GreaterThan), TOKEN(LessEqual), TOKEN(GreaterEqual),
TOKEN(ShiftLeft), TOKEN(ShiftRight), 
TOKEN(Plus), TOKEN(Minus), 
TOKEN(Asterisk), TOKEN(Slash), TOKEN(Modulus),
TOKEN(Increment), TOKEN(Decrement), TOKEN(UnaryNot), TOKEN(UnaryExor), TOKEN(Sizeof), TOKEN(Cast),
TOKEN(LeftSquareBracket), TOKEN(RightSquareBracket), TOKEN(Dot), TOKEN(Arrow), 
TOKEN(OpenBracket), TOKEN(CloseBracket),
TOKEN(Identifier), TOKEN(IntegerConstant), TOKEN(FPConstant), TOKEN(StringConstant), TOKEN(CharacterConstant),
TOKEN(Semicolon), TOKEN(Ellipsis),
TOKEN(LeftBrace), TOKEN(RightBrace),
TOKEN(IntType), TOKEN(CharType), TOKEN(FloatType), TOKEN(DoubleType), TOKEN(VoidType), TOKEN(EnumType),
TOKEN(LongType), TOKEN(SignedType), TOKEN(ShortType), TOKEN(StaticType), TOKEN(AutoType), TOKEN(RegisterType), TOKEN(ExternType), TOKEN(StructType), TOKEN(UnionType), TOKEN(UnsignedType), TOKEN(Typedef),
TOKEN(Continue), TOKEN(Do), TOKEN(Else), TOKEN(For), TOKEN(Goto), TOKEN(If), TOKEN(While), TOKEN(Break), TOKEN(Switch), TOKEN(Case), TOKEN(Default), TOKEN(Return),
TOKEN(HashDefine), TOKEN(HashInclude), TOKEN(HashIf), TOKEN(HashIfdef), TOKEN(HashIfndef), TOKEN(HashElse), TOKEN(HashEndif),
TOKEN(New), TOKEN(Delete),
TOKEN(OpenMacroBracket),
TOKEN(Interface), TOKEN(Class), TOKEN(Module), TOKEN(Implements),
TOKEN(Public),
TOKEN(Private),
TOKEN(Property),
TOKEN(Scope),

TOKEN(EOF),
TOKEN(EndOfLine),
TOKEN(EndOfFunction),
